Repository devpalsPlus/frontend, pull requests merged in 2025-01, with the labels that each got.

#4 Feat/#2
  src/App.css
  src/App.tsx
  src/index.css
  src/main.tsx
  src/style/global.ts
  src/style/theme.ts
Labels: ⛏기능

#11 pretendard 적용 오류 해결 (issue #8)
  index.html
  src/App.tsx
Labels: 👀버그

#15 Avatar공통 컴포넌트 생성 (issue #12)
  src/assets/user.svg
  src/components/common/avatar/Avatar.styled.ts
  src/components/common/avatar/Avatar.tsx
Labels: ⛏기능

#16 Feat/#9
  package-lock.json
  package.json
  src/components/common/inputComponent.tsx
  src/constants/index.ts
  src/pages/createProject/CreateProject.styled.ts
  src/pages/createProject/CreateProject.tsx
  src/style/theme.ts
Labels: ⛏기능

#23 Avatar 컴포넌트 스토리 작성(issue #21)
  package-lock.json
  package.json
  src/components/common/avatar/Avatar.stories.tsx
  src/components/common/avatar/Avatar.styled.ts
  src/pages/main/Main.tsx
Labels: ⛏기능, 🔧테스트

#25 Feat/#14
  package-lock.json
  package.json
  src/api/http.ts
  src/assets/logo.png
  src/components/auth/InputText.styled.ts
  src/components/auth/InputText.tsx
  src/components/common/title/Title.styled.ts
  src/components/common/title/Title.tsx
  src/pages/login/Login.styled.ts
  src/pages/login/Login.tsx
  src/store/authStore.ts
  src/style/theme.ts
Labels: ⛏기능

#26 feat : zod 유효성 검사 추가
  src/components/common/inputComponent.tsx
  src/constants/index.ts
  src/pages/createProject/CreateProject.tsx
Labels: ⛏기능

#27 layout 컴포넌트 구현 (issue #24)
  package-lock.json
  src/App.tsx
  src/assets/mainlogo.svg
  src/components/common/avatar/Avatar.styled.ts
  src/components/common/avatar/Avatar.tsx
  src/components/common/header/Header.styled.ts
  src/components/common/header/Header.tsx
  src/components/common/layout/Layout.styled.ts
  src/components/common/layout/Layout.tsx
  src/components/common/layout/sidebar/LayoutSidebar.tsx
  src/pages/error/Error.tsx
  src/routes/AppRoutes.tsx
  src/style/theme.ts
Labels: ⛏기능

#29 마크 에디터 추가
  .gitignore
  package-lock.json
  package.json
  src/components/createProjectComponents/ markdownEditor/MdEditorInput.tsx
  src/components/createProjectComponents/LanguageComponent.styled.ts
  src/components/createProjectComponents/LanguageComponent.tsx
  src/components/createProjectComponents/MozipCategory.styled.ts
  src/components/createProjectComponents/MozipCategoryComponent.tsx
  src/components/createProjectComponents/inputComponent.tsx
  src/components/createProjectComponents/markdownEditor/MdEditorInput.styled.ts
  src/components/markdownEditor/MdEditorInput.styled.ts
  src/components/markdownEditor/MdEditorInput.tsx
  src/constants/index.ts
  src/pages/apply/Apply.styled.ts
  src/pages/apply/Apply.tsx
  src/pages/createProject/CreateProject.styled.ts
  src/pages/createProject/CreateProject.tsx
Labels: ⛏기능

#33 DropDown 컴포넌트 구현 (issue #32)
  src/api/http.ts
  src/components/common/dropDown/DropDown.styled.ts
  src/components/common/dropDown/DropDown.tsx
  src/components/common/header/Header.styled.ts
  src/components/common/header/Header.tsx
  src/components/common/layout/Layout.styled.ts
  src/routes/AppRoutes.tsx
Labels: ⛏기능

#35 로그인페이지-validation 구현
  src/components/auth/InputText.styled.ts
  src/components/auth/InputText.tsx
  src/pages/login/Login.styled.ts
  src/pages/login/Login.tsx
Labels: ⛏기능

#41 MSW세팅
  .gitignore
  .prettierrc
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/api/http.ts
  src/api/index.ts
  src/api/myProjectList.api.ts
  src/main.tsx
  src/mock/browser.ts
  src/mock/index.ts
  src/mock/manageProjectList.ts
  src/models/index.ts
  src/models/manageMyProject.ts
  src/pages/manage/myProjectList/MyProjectList.tsx
Labels: ⛏기능

#44 Feat/#36 회원가입페이지 UI 및 validation
  package-lock.json
  src/api/auth.api.ts
  src/api/http.ts
  src/components/auth/InputText.styled.ts
  src/components/auth/InputText.tsx
  src/components/common/title/Title.styled.ts
  src/pages/login/Login.styled.ts
  src/pages/login/Login.tsx
  src/pages/register/Register.tsx
Labels: ⛏기능

#50 Feat/#45 비밀번호 재설정페이지 UI 및 validation
  src/api/auth.api.ts
  src/api/http.api.ts
  src/hooks/useEmailVerification.ts
  src/models/auth.ts
  src/pages/changePassword/ChangePassword.tsx
  src/pages/login/Login.tsx
  src/pages/register/Register.tsx
Labels: ⛏기능

#56 버튼 공통 컴포넌트 구현(issue #42)
  .storybook/preview.ts
  .storybook/preview.tsx
  package-lock.json
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/Button.styled.ts
  src/components/common/Button/Button.tsx
  src/components/common/layout/Layout.styled.ts
  src/components/common/layout/home/Layout.styled.ts
  src/components/common/layout/home/Layout.tsx
  src/components/index.ts
  src/style/theme.ts
Labels: ⛏기능

#57 Feat/#51
  package-lock.json
  package.json
  src/App.tsx
  src/api/createProject.api.ts
  src/api/joinProject.api.ts
  src/components/createProjectComponents/FieldCategoryComponent.tsx
  src/components/createProjectComponents/LanguageComponent.styled.ts
  src/components/createProjectComponents/LanguageComponent.tsx
  src/components/createProjectComponents/MozipCategory.styled.ts
  src/components/createProjectComponents/MozipCategoryComponent.tsx
  src/components/createProjectComponents/ProjectInformation.tsx
  src/components/createProjectComponents/ProjectInformationInput.tsx
  src/components/createProjectComponents/editor/MarkdownEditor.tsx
  src/components/createProjectComponents/inputComponent.tsx
  src/components/createProjectComponents/inputComponent2.tsx
  src/components/markdownEditor/MdEditorInput.styled.ts
  src/components/markdownEditor/MdEditorInput.tsx
  src/constants/homeConstants.ts
  src/constants/index.ts
  src/hooks/useJoinProject.ts
  src/models/createProject.ts
  src/models/joinProject.ts
  src/pages/apply/Apply.styled.ts
  src/pages/apply/Apply.tsx
  src/pages/createProject/CreateProject.tsx
  src/pages/projectDetail/ProjectDetail.styled.ts
  src/pages/projectDetail/ProjectDetail.tsx
  src/routes/AppRoutes.tsx
  src/util/format.ts
  src/util/handleClick.util.ts
Labels: ⛏기능, 🛠개선

#59 프로젝트 상세정보 페이지 구현 Feat/#55
  src/api/joinProject.api.ts
  src/components/createProjectComponents/LanguageComponent.styled.ts
  src/components/createProjectComponents/MozipCategory.styled.ts
  src/components/createProjectComponents/ProjectInformation.styled.ts
  src/components/createProjectComponents/ProjectInformation.tsx
  src/components/createProjectComponents/editor/MarkdownEditor.styled.ts
  src/constants/index.ts
  src/hooks/useJoinProject.ts
  src/models/projectDetail.ts
  src/pages/apply/Apply.tsx
  src/pages/createProject/CreateProject.styled.ts
  src/pages/createProject/CreateProject.tsx
  src/pages/projectDetail/ProjectDetail.styled.ts
  src/pages/projectDetail/ProjectDetail.tsx
  src/util/format.ts
Labels: ⛏기능

#62 Feat/#53 리팩토링 - 버튼, 컨트롤러
  package-lock.json
  src/assets/logo.png
  src/components/common/header/Header.tsx
  src/components/common/title/Title.styled.ts
  src/constants/authConstants.ts
  src/pages/changePassword/ChangePassword.tsx
  src/pages/login/Login.styled.ts
  src/pages/login/Login.tsx
  src/pages/register/Register.tsx
  src/routes/AppRoutes.tsx
Labels: 🛠개선

#66 Feat/#64
  src/components/applyComponents/careersComponent/CareersComponent.styled.ts
  src/components/applyComponents/careersComponent/CareersComponent.tsx
  src/components/applyComponents/phoneComponent/PhoneComponent.styled.ts
  src/components/applyComponents/phoneComponent/PhoneComponent.tsx
  src/components/common/positionButton/PositionButton.styled.ts
  src/components/common/positionButton/PositionButton.tsx
  src/components/createProjectComponents/editor/MarkdownEditor.tsx
  src/components/createProjectComponents/editor/MarkdownEditorView.tsx
  src/components/createProjectComponents/inputComponent.tsx
  src/components/createProjectComponents/inputComponent2.tsx
  src/components/createProjectComponents/projectInformationInput/ProjectInformationInput.styled.ts
  src/components/createProjectComponents/projectInformationInput/ProjectInformationInput.tsx
  src/components/createProjectComponents/projectInformationInput/fieldCategoryComponent/FieldCategoryComponent.styled.ts
  src/components/createProjectComponents/projectInformationInput/fieldCategoryComponent/FieldCategoryComponent.tsx
  src/components/createProjectComponents/projectInformationInput/languageComponent/LanguageComponent.styled.ts
  src/components/createProjectComponents/projectInformationInput/languageComponent/LanguageComponent.tsx
  src/components/createProjectComponents/projectInformationInput/positionComponent/PositionComponent.styled.ts
  src/components/createProjectComponents/projectInformationInput/positionComponent/PositionComponent.tsx
  src/components/createProjectComponents/projectInformationText/ProjectInformation.styled.ts
  src/components/createProjectComponents/projectInformationText/ProjectInformation.tsx
  src/components/inputComponent/inputComponent.styled.ts
  src/components/inputComponent/inputComponent.tsx
  src/constants/index.ts
  src/hooks/useControllerForm.ts
  src/pages/apply/Apply.styled.ts
  src/pages/apply/Apply.tsx
  src/pages/createProject/CreateProject.styled.ts
  src/pages/createProject/CreateProject.tsx
  src/pages/projectDetail/ProjectDetail.styled.ts
  src/pages/projectDetail/ProjectDetail.tsx
Labels: 🛠개선, 👀버그

#65 프로젝트 모집 관리 페이지 구현(issue #58)
  src/api/myProjectList.api.ts
  src/assets/createProjectButton.svg
  src/components/common/Button/Button.stories.tsx
  src/components/common/avatar/AvartarList.tsx
  src/components/common/avatar/Avatar.styled.ts
  src/components/common/avatar/AvatarList.styled.ts
  src/components/manageProjects/Card.styled.ts
  src/components/manageProjects/Card.tsx
  src/components/manageProjects/CardList.styled.ts
  src/components/manageProjects/CardList.tsx
  src/hooks/index.ts
  src/hooks/useManagedProjects.ts
  src/mock/manageProjectList.ts
  src/models/manageMyProject.ts
  src/pages/manage/myProjectList/MyProjectList.styled.ts
  src/pages/manage/myProjectList/MyProjectList.tsx
  src/style/theme.ts
Labels: ⛏기능

#69 Feat/#63 auth페이지 - api 연동
  src/api/auth.api.ts
  src/api/http.api.ts
  src/components/common/header/Header.tsx
  src/hooks/useAuth.ts
  src/pages/changePassword/ChangePassword.tsx
  src/pages/login/Login.tsx
  src/pages/projectDetail/ProjectDetail.tsx
  src/pages/register/Register.tsx
Labels: ⛏기능

#73 Feat/#70 auth 관련 페이지 - 토큰 만료시 재발급 및 상태 유지 처리
  src/api/http.api.ts
  src/components/common/header/Header.tsx
  src/hooks/useAlert.ts
  src/hooks/useAuth.ts
  src/routes/AppRoutes.tsx
  src/store/authStore.ts
Labels: ⛏기능

#77 프로젝트 관리 페이지 개선 (issue #72)
  package-lock.json
  package.json
  setupTests.ts
  src/App.tsx
  src/components/common/avatar/AvartarList.tsx
  src/components/manageProjects/Card.tsx
  src/components/manageProjects/CardList.tsx
  src/constants/routes.ts
  src/hooks/queries/keys.ts
  src/hooks/useManagedProjects.ts
  src/mock/browser.ts
  src/mock/manageProjectList.ts
  src/models/manageMyProject.ts
  src/pages/manage/myProjectList/MyProjectList.styled.ts
  src/pages/manage/myProjectList/MyProjectList.tsx
  src/routes/AppRoutes.tsx
  src/util/__tests__/render.tsx
  vite.config.ts
  vitest.d.ts
Labels: ⛏기능, 🛠개선

#80 Feat/#76 auth페이지 tanstackquery 적용, 마이페이지,유저페이지 세팅
  src/App.tsx
  src/api/auth.api.ts
  src/components/auth/InputText.styled.ts
  src/components/common/header/Header.tsx
  src/components/common/sidebar/Sidebar.styled.ts
  src/components/common/sidebar/Sidebar.tsx
  src/components/mypage/appliedProject/MyApplyProject.styled.ts
  src/components/mypage/appliedProject/MyApplyProject.tsx
  src/components/mypage/joinedProject/MyJoinProjects.styled.ts
  src/components/mypage/joinedProject/MyJoinProjects.tsx
  src/components/mypage/myProfile/myProfile.styled.ts
  src/components/mypage/myProfile/myProfile.tsx
  src/components/userPage/joinedProject/UserJoinProject.styled.ts
  src/components/userPage/joinedProject/UserJoinProject.tsx
  src/components/userPage/userProfile/UserProfile.styled.ts
  src/components/userPage/userProfile/UserProfile.tsx
  src/constants/routes.ts
  src/hooks/useAuth.ts
  src/hooks/useEmailVerification.ts
  src/hooks/useNicknameVerification.ts
  src/models/auth.ts
  src/pages/changePassword/ChangePassword.tsx
  src/pages/login/Login.styled.ts
  src/pages/login/Login.tsx
  src/pages/mypage/MyPage.styled.ts
  src/pages/mypage/MyPage.tsx
  src/pages/register/Register.tsx
  src/pages/userpage/UserPage.styled.ts
  src/pages/userpage/UserPage.tsx
  src/pages/users/myEnteredProject/MyEnteredProject.tsx
  src/pages/users/myProfile/MyProfile.tsx
  src/pages/users/otherUserProfile/OtherUserProfile.tsx
  src/pages/users/otherUserProject/OtherUserProject.tsx
  src/routes/AppRoutes.tsx
Labels: ⛏기능, 🛠개선

#83 로딩스피너, 라우팅 보호 컴포넌트 구현 (issue #81)
  src/components/common/ProtectRoute.tsx
  src/components/common/dropDown/DropDown.styled.ts
  src/components/common/header/Header.styled.ts
  src/components/common/header/Header.tsx
  src/components/common/loadingSpinner/LoadingSpinner.styled.ts
  src/components/common/loadingSpinner/LoadingSpinner.tsx
  src/components/common/modal/ScrollPreventor.styled.ts
  src/components/common/modal/ScrollPreventor.tsx
  src/hooks/useManagedProjects.ts
  src/routes/AppRoutes.tsx
Labels: ⛏기능, 🛠개선

#88 버그 수정
  src/components/common/skillTagBox/SkillTagBox.tsx
  src/components/common/skillTagBox/skillTag/SkillTag.tsx
  src/components/common/skillTagBox/skillTag/skillTagImg/SkillTagImg.tsx
  src/components/home/searchFiltering/filteringContents/FilteringContents.tsx
  src/pages/apply/Apply.tsx
  src/pages/projectDetail/ProjectDetail.tsx
  src/util/handleClick.util.ts
Labels: 👀버그

#89 Feat/#75
  src/components/common/skillTagBox/skillTag/SkillTag.tsx
  src/components/common/skillTagBox/skillTag/skillTagImg/SkillTagImg.tsx
  src/components/home/projectCardLists/ProjectCardLists.tsx
  src/components/home/projectCardLists/cardList/CardList.tsx
  src/components/home/projectCardLists/pagination/Pagination.styled.ts
  src/components/home/projectCardLists/pagination/Pagination.tsx
  src/components/home/searchFiltering/filteringContents/FilteringContents.styled.ts
  src/components/home/searchFiltering/search/Search.styled.ts
  src/components/home/searchFiltering/search/Search.tsx
  src/constants/homeConstants.ts
  src/hooks/useProjectCardListData.ts
  src/pages/home/Home.tsx
  src/reducer/pagination-reducer.ts
Labels: ⛏기능, 👀버그

#91 Feat/#82 마이페이지 (마이프로필 조회 및 수정)
  package-lock.json
  package.json
  src/api/mypage.api.ts
  src/components/auth/InputText.styled.ts
  src/components/auth/InputText.tsx
  src/components/common/sidebar/Sidebar.styled.ts
  src/components/mypage/myProfile/myProfile.styled.ts
  src/components/mypage/myProfile/myProfile.tsx
  src/components/mypage/myProfile/optionBox.styled.ts
  src/components/mypage/myProfile/optionBox.tsx
  src/constants/authConstants.ts
  src/hooks/queries/keys.ts
  src/hooks/useMyProfileInfo.ts
  src/models/myInfo.ts
  src/pages/login/Login.tsx
  src/pages/mypage/MyPage.styled.ts
  src/pages/mypage/MyPage.tsx
Labels: ⛏기능, 🛠개선

#93 지원자 리스트 탭 구현 (issue #86)
  src/api/applicantInfo.api.ts
  src/components/common/infoCard/InfoCard.styled.ts
  src/components/common/infoCard/InfoCard.tsx
  src/components/manageProjects/RecruitmentDate.styled.ts
  src/components/manageProjects/RecruitmentDate.tsx
  src/components/manageProjects/applicantInfo/ApplicantInfo.styled.ts
  src/components/manageProjects/applicantInfo/ApplicantInfo.tsx
  src/components/manageProjects/applicantList/ApplicantItem.styled.ts
  src/components/manageProjects/applicantList/ApplicantItem.tsx
  src/components/manageProjects/applicantList/ApplicantList.styled.ts
  src/components/manageProjects/applicantList/ApplicantList.tsx
  src/constants/sidebarItems.tsx
  src/hooks/queries/keys.ts
  src/hooks/useApllicantInfo.ts
  src/mock/applicant.ts
  src/mock/browser.ts
  src/mock/manageProjectList.ts
  src/mock/mockApplicantData.json
  src/mock/mockProjectDetail.json
  src/mock/mockProjectList.json
  src/mock/projectDetail.ts
  src/models/applicant.ts
  src/models/manageMyProject.ts
  src/pages/manage/myProjectParticipantsPass/MyProjectVolunteersPass.tsx
  src/pages/manage/myProjectVolunteer/MyProjectVolunteer.styled.ts
  src/pages/manage/myProjectVolunteer/MyProjectVolunteer.tsx
  src/routes/AppRoutes.tsx
  src/style/theme.ts
Labels: ⛏기능

#102 Feat/#95 프로필 이미지, 닉네임 + 헤더 버그 수정 + 사이드바 버튼 활성화
  package-lock.json
  src/api/mypage.api.ts
  src/api/userpage.api.ts
  src/assets/defaultImg.png
  src/components/common/avatar/Avatar.tsx
  src/components/common/header/Header.styled.ts
  src/components/common/header/Header.tsx
  src/components/common/sidebar/Sidebar.styled.ts
  src/components/common/sidebar/Sidebar.tsx
  src/components/common/sidebar/editMyProfileImg/EditMyProfileImg.styled.ts
  src/components/common/sidebar/editMyProfileImg/EditMyProfileImg.tsx
  src/components/mypage/myProfile/myProfile.tsx
  src/hooks/queries/keys.ts
  src/hooks/useMyInfo.ts
  src/hooks/useUserInfo.ts
  src/models/userInfo.ts
  src/pages/changePassword/ChangePassword.tsx
  src/pages/login/Login.tsx
  src/pages/mypage/MyPage.styled.ts
  src/pages/mypage/MyPage.tsx
  src/pages/register/Register.tsx
  src/pages/userpage/UserPage.tsx
Labels: ⛏기능, 🛠개선, 👀버그

#103 지원자 정보 탭 구현(issue #94)
  src/api/applicant.api.ts
  src/api/applicantInfo.api.ts
  src/components/common/avatar/AvartarList.tsx
  src/components/common/infoCard/InfoCard.styled.ts
  src/components/common/layout/ApplicantViewLayout.styled.ts
  src/components/common/layout/ApplicantViewLayout.tsx
  src/components/manageProjects/applicantInfo/ApplicantInfo.styled.ts
  src/components/manageProjects/applicantInfo/ApplicantInfo.tsx
  src/components/manageProjects/applicantInfo/LabelWithContent.styled.ts
  src/components/manageProjects/applicantInfo/LabelWithContent.tsx
  src/components/manageProjects/applicantList/ApplicantItem.styled.ts
  src/components/manageProjects/applicantList/ApplicantItem.tsx
  src/components/manageProjects/applicantList/ApplicantList.tsx
  src/hooks/queries/keys.ts
  src/hooks/useApllicantList.ts
  src/hooks/useApplicantInfo.ts
  src/mock/applicant.ts
  src/mock/browser.ts
  src/mock/mockApplicantData.json
  src/mock/mockApplicantsData.json
  src/models/applicant.ts
  src/pages/manage/myProjectVolunteer/MyProjectVolunteer.styled.ts
  src/pages/manage/myProjectVolunteer/MyProjectVolunteer.tsx
  src/routes/AppRoutes.tsx
Labels: ⛏기능

#106 메인 페이지 스타일 수정
  src/components/home/banner/Banner.styled.ts
  src/components/home/projectCardLists/cardList/CardList.styled.ts
  src/components/home/projectStats/ProjectStats.styled.ts
  src/components/home/projectStats/projectStat/ProjectStat.styled.ts
  src/components/home/searchFiltering/SearchFiltering.styled.ts
  src/components/home/searchFiltering/filteringContents/FilteringContents.styled.ts
  src/components/home/searchFiltering/filteringContents/FilteringContents.tsx
  src/components/home/searchFiltering/filteringContents/filtering/Filtering.styled.ts
  src/components/home/searchFiltering/search/Search.styled.ts
Labels: 🛠개선

#107 로딩 성능 개선(issue #105)
  src/routes/AppRoutes.tsx
Labels: 🛠개선

#109 유저페이지 - 유저 프로필 조회
  src/assets/loadingImg.svg
  src/components/common/header/Header.tsx
  src/components/common/sidebar/Sidebar.tsx
  src/components/common/sidebar/editMyProfileImg/EditMyProfileImg.tsx
  src/components/home/searchFiltering/filteringContents/FilteringContents.styled.ts
  src/components/home/searchFiltering/filteringContents/filtering/Filtering.styled.ts
  src/components/mypage/myProfile/myProfile.styled.ts
  src/components/mypage/myProfile/myProfile.tsx
  src/components/userPage/userProfile/UserProfile.tsx
  src/hooks/useMyInfo.ts
  src/pages/mypage/MyPage.tsx
  src/pages/userpage/UserPage.tsx
Labels: ⛏기능

#119 마이페이지 - 지원프로젝트(불합리스트) 조회
  src/api/mypage.api.ts
  src/components/mypage/appliedProject/MyApplyProject.styled.ts
  src/components/mypage/appliedProject/MyApplyProject.tsx
  src/components/mypage/appliedProject/MyStatus.styled.ts
  src/components/mypage/appliedProject/MyStatus.tsx
  src/components/mypage/joinedProject/MyJoinProjects.tsx
  src/components/mypage/joinedProject/Project.styled.ts
  src/components/mypage/joinedProject/Project.tsx
  src/components/mypage/myProfile/myProfile.styled.ts
  src/components/mypage/myProfile/myProfile.tsx
  src/components/userPage/userProfile/UserProfile.tsx
  src/constants/authConstants.ts
  src/hooks/queries/keys.ts
  src/hooks/useMyInfo.ts
  src/models/userProject.ts
  src/store/authStore.ts
Labels: ⛏기능, 🛠개선

#121 버그 및 스타일 수정
  src/components/applyComponents/careersComponent/CareersComponent.styled.ts
  src/components/applyComponents/careersComponent/CareersComponent.tsx
  src/components/applyComponents/careersComponent/careersInputComponent/CareersComponentInput.styled.ts
  src/components/applyComponents/careersComponent/careersInputComponent/CareersComponentInput.tsx
  src/components/common/ProtectRoute.tsx
  src/components/projectFormComponents/FieldCategoryComponent.tsx
  src/components/projectFormComponents/ProjectInformation.tsx
  src/components/projectFormComponents/projectInformationInput/ProjectInformationInput.styled.ts
  src/components/projectFormComponents/projectInformationInput/languageComponent/LanguageComponent.styled.ts
  src/components/projectFormComponents/projectInformationInput/positionComponent/PositionComponent.styled.ts
  src/components/projectFormComponents/projectInformationText/ProjectInformation.styled.ts
  src/components/projectFormComponents/projectInformationText/ProjectInformation.tsx
  src/pages/apply/Apply.styled.ts
  src/pages/apply/Apply.tsx
  src/pages/projectDetail/ProjectDetail.styled.ts
  src/pages/projectDetail/ProjectDetail.tsx
  src/routes/AppRoutes.tsx
Labels: 🛠개선, 👀버그

#125 지원자 합, 불합 기능 구현(issue #115)
  src/api/applicant.api.ts
  src/components/common/avatar/Avatar.tsx
  src/components/common/noContent/NoContent.styled.ts
  src/components/common/noContent/NoContent.tsx
  src/components/manageProjects/Card.tsx
  src/components/manageProjects/applicantInfo/ApplicantInfo.tsx
  src/components/manageProjects/applicantList/ApplicantItem.styled.ts
  src/components/manageProjects/applicantList/PassNonPassButton.styled.ts
  src/components/manageProjects/applicantList/PassNonPassButton.tsx
  src/hooks/useApllicantList.ts
  src/hooks/usePassNonPass.ts
  src/mock/applicant.ts
  src/mock/browser.ts
  src/pages/manage/myProjectVolunteer/MyProjectVolunteer.styled.ts
  src/pages/manage/myProjectVolunteer/MyProjectVolunteer.tsx
Labels: ⛏기능

#132 지원자 리스트 페이지 개선(issue #126)
  src/components/manageProjects/Card.styled.ts
  src/components/manageProjects/Card.tsx
  src/components/manageProjects/applicantInfo/ApplicantInfo.tsx
  src/components/manageProjects/applicantList/PassNonPassButton.styled.ts
  src/components/manageProjects/applicantList/PassNonPassButton.tsx
  src/constants/sidebarItems.tsx
  src/hooks/useApllicantList.ts
  src/hooks/useApplicantInfo.ts
  src/hooks/usePassNonPass.ts
  src/models/manageMyProject.ts
  src/pages/manage/myProjectVolunteer/MyProjectVolunteer.styled.ts
  src/pages/manage/myProjectVolunteer/MyProjectVolunteer.tsx
Labels: 🛠개선

#134 유저페이지 - 유저 참여 프로젝트 리스트 조회
  src/api/http.api.ts
  src/api/mypage.api.ts
  src/api/userpage.api.ts
  src/components/common/avatar/Avatar.tsx
  src/components/mypage/Spinner.styled.ts
  src/components/mypage/Spinner.tsx
  src/components/mypage/appliedProject/MyApplyProject.styled.ts
  src/components/mypage/appliedProject/MyApplyProject.tsx
  src/components/mypage/appliedProject/MyStatus.styled.ts
  src/components/mypage/joinedProject/MyJoinProjects.styled.ts
  src/components/mypage/joinedProject/MyJoinProjects.tsx
  src/components/mypage/joinedProject/Project.styled.ts
  src/components/mypage/joinedProject/Project.tsx
  src/components/mypage/myProfile/myProfile.styled.ts
  src/components/userPage/joinedProject/UserJoinProject.styled.ts
  src/components/userPage/joinedProject/UserJoinProject.tsx
  src/components/userPage/userProfile/UserProfile.styled.ts
  src/hooks/queries/keys.ts
  src/hooks/useMyInfo.ts
  src/hooks/useUserInfo.ts
  src/models/userProject.ts
  src/pages/changePassword/ChangePassword.styled.ts
  src/pages/mypage/MyPage.tsx
  src/pages/register/Register.styled.ts
  src/pages/userpage/UserPage.styled.ts
  src/pages/userpage/UserPage.tsx
  src/routes/AppRoutes.tsx
Labels: ⛏기능, 🛠개선

#138 ci 스크립트 작성(issue #137)
  .github/workflows/front_ci.yml
  setupTests.ts
Labels: 🔧테스트

#136 공고 상세 페이지 예외 처리
  src/components/projectFormComponents/projectInformationInput/ProjectInformationInput.tsx
  src/components/projectFormComponents/projectInformationText/ProjectInformation.styled.ts
  src/components/projectFormComponents/projectInformationText/ProjectInformation.tsx
  src/hooks/useAuth.ts
  src/models/auth.ts
  src/models/projectDetail.ts
  src/pages/apply/Apply.tsx
  src/pages/createProject/CreateProject.tsx
  src/pages/modifyProject/ModifyProject.tsx
  src/pages/projectDetail/ProjectDetail.tsx
  src/store/authStore.ts
Labels: 🛠개선, 👀버그

#139 상세 공고 페이지 버그 수정
  src/components/projectFormComponents/projectInformationInput/ProjectInformationInput.tsx
  src/components/projectFormComponents/projectInformationInput/fieldCategoryComponent/FieldCategoryComponent.tsx
  src/components/projectFormComponents/projectInformationInput/languageComponent/LanguageComponent.tsx
  src/hooks/useUpdateProject.ts
  src/pages/apply/Apply.tsx
  src/pages/createProject/CreateProject.tsx
  src/pages/modifyProject/ModifyProject.tsx
  src/pages/projectDetail/ProjectDetail.tsx
Labels: 🛠개선, 👀버그

#142 github action 설정
  .github/workflows/front_ci-cd.yml
  src/api/projectLists.api.ts
  src/components/applyComponents/careersComponent/CareersComponent.tsx
  src/components/common/Button/Button.tsx
  src/components/common/layout/sidebar/LayoutSidebar.tsx
  src/components/projectFormComponents/editor/MarkdownEditor.tsx
  src/components/projectFormComponents/projectInformationInput/positionComponent/PositionComponent.tsx
  src/context/SearchFilteringContext.tsx
  src/pages/apply/Apply.tsx
  src/pages/error/Error.tsx
  src/pages/main/Main.tsx
  src/store/authStore.ts
  src/util/__tests__/render.tsx
  src/util/handleClick.util.ts
Labels: 🛠개선

#146 feat : CI/CD 오류 해결
  .github/workflows/front_ci-cd.yml
Labels: 👀버그

#149 합/ 불합 페이지 구현 (issue #144)
  src/api/applicant.api.ts
  src/components/common/noContent/NoContent.tsx
  src/components/manageProjects/ProjectHeader.styled.ts
  src/components/manageProjects/ProjectHeader.tsx
  src/components/manageProjects/passNonPassList/PassNonPassItem.styled.ts
  src/components/manageProjects/passNonPassList/PassNonPassItem.tsx
  src/components/manageProjects/passNonPassList/PassNonPassList.styled.ts
  src/components/manageProjects/passNonPassList/PassNonPassList.tsx
  src/hooks/queries/keys.ts
  src/hooks/usePassNonPassList.ts
  src/hooks/usePassNonPassMutation.ts
  src/mock/applicant.ts
  src/mock/browser.ts
  src/mock/mockPassNonPassListData.json
  src/pages/manage/myProjectParticipantsPass/MyProjectVolunteersPass.styled.ts
  src/pages/manage/myProjectParticipantsPass/MyProjectVolunteersPass.tsx
  src/pages/manage/myProjectVolunteer/MyProjectVolunteer.styled.ts
  src/pages/manage/myProjectVolunteer/MyProjectVolunteer.tsx
  src/routes/AppRoutes.tsx
Labels: ⛏기능

#153 auth페이지, 마이페이지, 유저페이지 미디어쿼리 적용
  src/components/auth/InputText.styled.ts
  src/components/common/avatar/Avatar.styled.ts
  src/components/common/header/Header.styled.ts
  src/components/common/layout/Layout.styled.ts
  src/components/common/sidebar/Sidebar.styled.ts
  src/components/common/title/Title.styled.ts
  src/components/mypage/appliedProject/MyApplyProject.styled.ts
  src/components/mypage/appliedProject/MyStatus.styled.ts
  src/components/mypage/joinedProject/MyJoinProjects.styled.ts
  src/components/mypage/joinedProject/Project.styled.ts
  src/components/mypage/myProfile/myProfile.styled.ts
  src/components/mypage/myProfile/optionBox.styled.ts
  src/components/userPage/userProfile/UserProfile.tsx
  src/mock/browser.ts
  src/mock/mockMypageAppliedProjectListData.json
  src/mock/mockMypageJoinedProjectListData.json
  src/mock/mockMypageProfileData.json
  src/mock/mockPositionTagData.json
  src/mock/mockSkillTagData.json
  src/mock/mockUserpageAppliedProjectListData.json
  src/mock/mockUserpageProfileData.json
  src/mock/mypage.ts
  src/mock/userpage.ts
  src/style/theme.ts
Labels: ⛏기능, 🛠개선

#151 지원자 리스트 페이지 - 렌더링 성능 개선(issue #150)
  src/components/common/sidebar/Sidebar.tsx
  src/components/manageProjects/ProjectHeader.tsx
  src/mock/browser.ts
  src/pages/manage/myProjectVolunteer/MyProjectVolunteer.tsx
Labels: 🛠개선

#156 모달창 디자인 수정 및 적용/notFound 페이지 생성
  src/assets/notFoundImg.svg
  src/components/common/header/Header.tsx
  src/components/common/modal/Modal.styled.ts
  src/components/common/modal/Modal.tsx
  src/components/common/page/notFoundPage/NotFoundPage.styled.ts
  src/components/common/page/notFoundPage/NotFoundPage.tsx
  src/components/common/sidebar/editMyProfileImg/EditMyProfileImg.tsx
  src/components/mypage/myProfile/myProfile.tsx
  src/constants/modalMessage.ts
  src/constants/routes.ts
  src/hooks/useAuth.ts
  src/hooks/useMyInfo.ts
  src/mock/auth.ts
  src/mock/browser.ts
  src/mock/mypage.ts
  src/pages/changePassword/ChangePassword.tsx
  src/pages/login/Login.tsx
  src/pages/register/Register.tsx
Labels: ⛏기능, 🛠개선

#163 반응형을 위한 미디어 쿼리 추가
  src/components/applyComponents/careersComponent/CareersComponent.styled.ts
  src/components/applyComponents/careersComponent/careersInputComponent/CareersComponentInput.styled.ts
  src/components/projectFormComponents/projectInformationText/ProjectInformation.styled.ts
  src/components/projectFormComponents/projectInformationText/ProjectInformation.tsx
  src/pages/apply/Apply.styled.ts
  src/pages/createProject/CreateProject.styled.ts
  src/pages/projectDetail/ProjectDetail.styled.ts
Labels: 🛠개선

#165 모집공고관리 페이지 반응형 구현(issue #162)
  src/components/common/infoCard/InfoCard.styled.ts
  src/components/common/layout/ApplicantViewLayout.styled.ts
  src/components/common/layout/ApplicantViewLayout.tsx
  src/components/common/layout/sidebar/LayoutSidebar.styled.ts
  src/components/common/layout/sidebar/LayoutSidebar.tsx
  src/components/common/sidebar/Sidebar.styled.ts
  src/components/manageProjects/Card.styled.ts
  src/components/manageProjects/CardList.styled.ts
  src/components/manageProjects/RecruitmentDate.styled.ts
  src/components/manageProjects/applicantInfo/ApplicantInfo.styled.ts
  src/components/manageProjects/applicantInfo/LabelWithContent.styled.ts
  src/components/manageProjects/applicantList/ApplicantItem.styled.ts
  src/components/manageProjects/applicantList/ApplicantList.styled.ts
  src/components/manageProjects/applicantList/PassNonPassButton.styled.ts
  src/components/manageProjects/passNonPassList/PassNonPassItem.styled.ts
  src/components/manageProjects/passNonPassList/PassNonPassList.styled.ts
  src/components/manageProjects/passNonPassList/SendResultButton.styled.ts
  src/pages/manage/myProjectList/MyProjectList.styled.ts
  src/pages/manage/myProjectList/MyProjectList.tsx
  src/pages/manage/myProjectParticipantsPass/MyProjectVolunteersPass.styled.ts
  src/pages/manage/myProjectVolunteer/MyProjectVolunteer.styled.ts
  src/pages/manage/myProjectVolunteer/MyProjectVolunteer.tsx
  src/routes/AppRoutes.tsx
  src/style/theme.ts
Labels: 🛠개선

#168 CI스크립트 추가 (issue #167)
  .github/workflows/chromatic.yml
  .github/workflows/front_ci.yml
  package-lock.json
  package.json
Labels: 🔧테스트
