Repository devpalsPlus/frontend, pull requests merged in 2025-05, with the labels that each got.

#267 fix : styled-component 빌드 에러 수정 (issue #266)
  src/components/manageProjects/Card.styled.ts
  src/components/manageProjects/RecruitmentDate.styled.ts
  src/pages/apply/Apply.styled.ts
  src/pages/apply/ApplyStep.styled.ts
  src/style/theme.ts
  src/styled.d.ts
  tsconfig.app.json
Labels: 👀버그

#268 신고 알림필터 수정, 답변 replier 추가 (#issue 265)
  src/components/common/header/Header.tsx
  src/components/mypage/ContentTab.tsx
  src/components/mypage/activityLog/inquiries/inquiry/Inquiry.styled.ts
  src/components/mypage/activityLog/inquiries/inquiry/Inquiry.tsx
  src/components/mypage/notifications/all/All.styled.ts
  src/components/mypage/notifications/all/All.tsx
  src/constants/customerService.ts
  src/models/alarm.ts
  src/style/theme.ts
Labels: 🛠개선

#270 문의하기 개선 (#issue 269)
  src/api/inquiry.api.ts
  src/components/common/header/Header.tsx
  src/components/mypage/activityLog/inquiries/inquiry/Inquiry.tsx
  src/constants/customerService.ts
  src/hooks/useMyInfo.ts
  src/hooks/usePostInquiry.ts
  src/models/apiCommon.ts
  src/pages/customerService/MoveInquiredLink.tsx
  src/pages/customerService/inquiry/Inquiry.styled.ts
  src/pages/customerService/inquiry/Inquiry.tsx
Labels: ⛏기능, 🛠개선

#273 ux수정 (#issue 272)
  src/components/common/ProtectRoute.tsx
  src/components/mypage/ContentTab.styled.ts
  src/components/mypage/ContentTab.tsx
  src/components/mypage/ScrollWrapper.styled.ts
  src/components/mypage/ScrollWrapper.tsx
  src/components/mypage/activityLog/ActivityLog.tsx
  src/components/mypage/activityLog/commentsActivity/CommentsActivity.tsx
  src/components/mypage/activityLog/inquiries/Inquiries.tsx
  src/components/mypage/joinedProject/MyJoinProjects.styled.ts
  src/components/mypage/joinedProject/MyJoinProjects.tsx
  src/components/mypage/myProfile/MyProfile.styled.ts
  src/components/mypage/myProfile/MyProfile.tsx
  src/components/mypage/myProfile/MyProfileWrapper.tsx
  src/components/mypage/myProfile/MyPropfileWrapper.styled.ts
  src/components/mypage/myProfile/editProfile/EditProfile.tsx
  src/components/mypage/myProfile/editProfile/editProfile.styled.ts
  src/components/mypage/myProfile/profile/Profile.styled.ts
  src/components/mypage/myProfile/profile/Profile.tsx
  src/components/mypage/notifications/all/All.tsx
  src/components/mypage/notifications/appliedProjects/AppliedProjects.tsx
  src/components/userPage/joinedProject/UserJoinProject.tsx
  src/constants/modalMessage.ts
  src/constants/routes.ts
  src/hooks/useModal.ts
  src/hooks/useMyInfo.ts
  src/pages/mypage/MyPage.styled.ts
  src/pages/userpage/UserPage.tsx
  src/routes/AppRoutes.tsx
Labels: ⛏기능, 🛠개선

#277 공지사항 ui, api 연결 (#isuue 276)
  src/App.tsx
  src/api/customerService.api.ts
  src/components/common/contentBorder/ContentBorder.styled.ts
  src/components/common/contentBorder/ContentBorder.tsx
  src/components/common/pagination/Pagination.styled.ts
  src/components/common/pagination/Pagination.tsx
  src/components/customerService/faq/FAQContent.styled.ts
  src/components/customerService/inquiry/Inquiry.styled.ts
  src/components/customerService/notice/NoticeList.styled.ts
  src/components/customerService/notice/NoticeList.tsx
  src/components/customerService/noticeDetail/NoticeDetailBundle.styled.ts
  src/components/customerService/noticeDetail/NoticeDetailBundle.tsx
  src/components/customerService/noticeDetail/bottom/NoticeDetailBottom.styled.ts
  src/components/customerService/noticeDetail/bottom/NoticeDetailBottom.tsx
  src/components/customerService/noticeDetail/bottom/button/ListButton.styled.ts
  src/components/customerService/noticeDetail/bottom/button/ListButton.tsx
  src/components/customerService/noticeDetail/bottom/button/OtherNoticeButton.styled.ts
  src/components/customerService/noticeDetail/bottom/button/OtherNoticeButton.tsx
  src/components/customerService/noticeDetail/content/NoticeDetailContent.styled.ts
  src/components/customerService/noticeDetail/content/NoticeDetailContent.tsx
  src/components/customerService/noticeDetail/header/NoticeDetailHeader.styled.ts
  src/components/customerService/noticeDetail/header/NoticeDetailHeader.tsx
  src/components/home/projectCardLists/ProjectCardLists.tsx
  src/components/mypage/activityLog/inquiries/Inquiries.styled.ts
  src/components/mypage/activityLog/inquiries/Inquiries.tsx
  src/constants/routes.ts
  src/hooks/queries/keys.ts
  src/hooks/useGetNotice.ts
  src/hooks/useGetNoticeDetail.ts
  src/models/customerService.ts
  src/pages/customerService/faq/FAQ.styled.ts
  src/pages/customerService/faq/FAQ.tsx
  src/pages/customerService/notice/Notice.styled.ts
  src/pages/customerService/notice/Notice.tsx
  src/pages/customerService/noticeDetail/NoticeDetail.styled.ts
  src/pages/customerService/noticeDetail/NoticeDetail.tsx
  src/pages/home/Home.tsx
  src/pages/mypage/MyPage.tsx
  src/routes/AppRoutes.tsx
Labels: ⛏기능, 🛠개선

#278 oauth 설정 (issue #271)
  src/assets/github.svg
  src/assets/google.svg
  src/assets/kakao.svg
  src/assets/naver.svg
  src/constants/authConstants.ts
  src/constants/routes.ts
  src/pages/login/Login.styled.ts
  src/pages/login/Login.tsx
  src/pages/login/LoginSuccess.tsx
  src/routes/AppRoutes.tsx
  src/store/authStore.ts
Labels: ⛏기능

#286 FAQ 개행 가능하게 수정 (#issue 284)
  src/components/customerService/faq/FAQContent.styled.ts
  src/components/customerService/noticeDetail/content/NoticeDetailContent.styled.ts
Labels: 🛠개선

#288 공고관리 카드 배치 수정 (#issue 287)
  src/components/manageProjects/Card.styled.ts
  src/components/manageProjects/CardList.styled.ts
  src/components/manageProjects/CardList.tsx
Labels: 🛠개선

#290 레이아웃 수정 (#issue 289)
  src/assets/banner.svg
  src/components/comment/CommentLayout.styled.ts
  src/components/comment/commentInput/CommentInput.styled.ts
  src/components/common/contentBorder/ContentBorder.styled.ts
  src/components/common/header/Header.styled.ts
  src/components/common/layout/Layout.styled.ts
  src/components/common/positionButton/PositionButton.styled.ts
  src/components/common/positionButton/PositionButton.tsx
  src/components/common/skillTagBox/SkillTagBox.tsx
  src/components/customerService/inquiry/Inquiry.styled.ts
  src/components/home/projectCardLists/ProjectCardLists.styled.ts
  src/components/home/projectCardLists/ProjectCardLists.tsx
  src/components/mypage/ContentTab.tsx
  src/components/projectFormComponents/inputComponent/InputComponent.styled.ts
  src/components/projectFormComponents/inputComponent/InputComponent.tsx
  src/components/projectFormComponents/projectInformationInput/ProjectInformationInput.tsx
  src/components/projectFormComponents/projectInformationInput/fieldCategoryComponent/FieldCategoryComponent.styled.ts
  src/components/projectFormComponents/projectInformationInput/fieldCategoryComponent/FieldCategoryComponent.tsx
  src/components/projectFormComponents/projectInformationInput/positionComponent/PositionComponent.styled.ts
  src/components/projectFormComponents/projectInformationInput/positionComponent/PositionComponent.tsx
  src/pages/createProject/CreateProject.styled.ts
  src/pages/home/Home.styled.ts
  src/pages/manage/myProjectList/MyProjectList.styled.ts
  src/pages/manage/myProjectList/MyProjectList.tsx
  src/pages/modifyProject/ModifyProject.styled.ts
  src/pages/mypage/MyPage.styled.ts
  src/pages/mypage/MyPage.tsx
  src/pages/projectDetail/ProjectDetail.styled.ts
  src/pages/projectDetail/ProjectDetail.tsx
Labels: 🛠개선

#285 평가하기 페이지 구현 (issue #263)
  src/api/evaluation.api.ts
  src/components/evaluation/EvaluationContent.styled.ts
  src/components/evaluation/EvaluationContent.tsx
  src/constants/evaluation.ts
  src/constants/routes.ts
  src/hooks/evaluationHooks/useEvaluationStep.ts
  src/hooks/evaluationHooks/useGetEvaluation.ts
  src/hooks/evaluationHooks/usePostEvaluation.ts
  src/hooks/queries/keys.ts
  src/models/evaluation.ts
  src/pages/evaluation/Evaluation.styled.ts
  src/pages/evaluation/Evaluation.tsx
  src/routes/AppRoutes.tsx
Labels: ⛏기능

#300 "지원하기" 페이지에 자잘한 기타 기능들 추가 및 자잘한 경로 에러 수정( issue #293, #299 )
  src/api/auth.api.ts
  src/components/common/header/Header.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalWrapper.tsx
  src/components/user/applyComponents/careersComponent/CareersComponent.styled.ts
  src/components/user/applyComponents/careersComponent/CareersComponent.tsx
  src/components/user/comment/commentComponent/CommentComponentLayout.tsx
  src/components/user/comment/commentComponent/commentComponent/CommentComponent.tsx
  src/components/user/comment/commentInput/CommentInput.styled.ts
  src/components/user/comment/commentInput/CommentInput.tsx
  src/components/user/comment/replyComponent/ReplyComponent.tsx
  src/components/user/evaluation/EvaluationContent.styled.ts
  src/components/user/home/banner/Banner.tsx
  src/components/user/home/projectCardLists/cardList/CardList.tsx
  src/components/user/home/searchFiltering/filteringContents/FilteringContents.tsx
  src/components/user/home/searchFiltering/filteringContents/filtering/Filtering.tsx
  src/components/user/manageProjects/passNonPassList/SendResultButton.styled.ts
  src/components/user/mypage/ContentTab.tsx
  src/components/user/mypage/activityLog/inquiries/inquiry/Inquiry.tsx
  src/components/user/mypage/joinedProject/Project.tsx
  src/components/user/mypage/myProfile/profile/Profile.tsx
  src/components/user/projectFormComponents/projectInformationInput/positionComponent/PositionComponent.styled.ts
  src/components/user/projectFormComponents/projectInformationInput/positionComponent/PositionComponent.tsx
  src/components/user/projectFormComponents/projectInformationText/ProjectInformation.tsx
  src/components/user/projectFormComponents/stepComponent/StepComponent.tsx
  src/components/user/userPage/userProfile/UserProfile.tsx
  src/constants/sidebarItems.tsx
  src/constants/user/modalMessage.ts
  src/context/ModalContext.tsx
  src/hooks/useModal.ts
  src/models/createProject.ts
  src/models/joinProject.ts
  src/models/projectDetail.ts
  src/pages/login/Login.tsx
  src/pages/login/LoginSuccess.tsx
  src/pages/user/apply/Apply.styled.ts
  src/pages/user/apply/ApplyStep.styled.ts
  src/pages/user/apply/ApplyStep.tsx
  src/pages/user/manage/myProjectParticipantsPass/MyProjectVolunteersPass.tsx
  src/pages/user/manage/myProjectVolunteer/MyProjectVolunteer.tsx
  src/pages/user/mypage/MyPage.tsx
  src/pages/user/projectDetail/ProjectDetail.styled.ts
  src/pages/user/projectDetail/ProjectDetail.tsx
  src/pages/user/register/Register.tsx
  src/pages/user/userpage/UserPage.tsx
Labels: ⛏기능, 🛠개선, 👀버그
