Repository devpalsPlus/frontend, pull requests merged in 2025-02, with the labels that each got.

#172 공용 모달 적용
  src/api/joinProject.api.ts
  src/components/applyComponents/careersComponent/CareersComponent.styled.ts
  src/components/applyComponents/careersComponent/careersInputComponent/CareersComponentInput.styled.ts
  src/components/applyComponents/phoneComponent/PhoneComponent.styled.ts
  src/components/applyComponents/phoneComponent/phoneComponentInput/PhoneComponentInput.styled.ts
  src/components/common/modal/Modal.tsx
  src/components/projectFormComponents/inputComponent/inputComponent.styled.ts
  src/components/projectFormComponents/projectInformationText/ProjectInformation.styled.ts
  src/constants/modalMessage.ts
  src/hooks/useApplyProject.ts
  src/hooks/useCreateProject.ts
  src/hooks/useModal.ts
  src/hooks/useUpdateProject.ts
  src/pages/apply/Apply.styled.ts
  src/pages/apply/Apply.tsx
  src/pages/createProject/CreateProject.tsx
  src/pages/modifyProject/ModifyProject.tsx
  src/pages/projectDetail/ProjectDetail.styled.ts
  src/pages/projectDetail/ProjectDetail.tsx
Labels: 🛠개선

#176 합/불합 리스트에서 지원자 클릭시 리다이렉트 후 정보 노출
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalCloseButton.tsx
  src/components/common/title/Title.styled.ts
  src/components/manageProjects/applicantList/ApplicantItem.tsx
  src/components/manageProjects/applicantList/ApplicantList.tsx
  src/components/manageProjects/passNonPassList/PassNonPassItem.styled.ts
  src/components/manageProjects/passNonPassList/PassNonPassItem.tsx
  src/components/manageProjects/passNonPassList/PassNonPassList.tsx
  src/hooks/useApplicantInfo.ts
  src/mock/mockApplicantsData.json
  src/mock/mockPassNonPassListData.json
  src/mock/mockProjectDetail.json
  src/pages/manage/myProjectParticipantsPass/MyProjectVolunteersPass.tsx
  src/pages/manage/myProjectVolunteer/MyProjectVolunteer.tsx
Labels: ⛏기능

#180 번들 사이즈 개선
  package-lock.json
  package.json
  vite.config.ts
Labels: 🛠개선

#191 보완(멘토님 피드백 반영, 아바타 로고 스타일 props 제거)
  src/components/common/ProtectRoute.tsx
  src/components/common/avatar/Avatar.styled.ts
  src/components/common/avatar/Avatar.tsx
  src/components/common/header/Header.tsx
  src/components/common/sidebar/Sidebar.styled.ts
  src/components/common/sidebar/Sidebar.tsx
  src/constants/modalMessage.ts
  src/hooks/useMyInfo.ts
  src/hooks/useUserInfo.ts
  src/routes/AppRoutes.tsx
Labels: 🛠개선

#190 웹 접근성 테스트
  .github/workflows/chromatic.yml
  .github/workflows/ui-test.yml
  .nvmrc
  .storybook/main.ts
  .storybook/preview.tsx
  .storybook/test-runner.ts
  package-lock.json
  package.json
  src/components/common/dropDown/DropDown.styled.ts
  src/components/common/dropDown/DropDown.tsx
  src/components/common/header/Header.styled.ts
  src/components/common/header/Header.tsx
  src/components/common/modal/Modal.styled.ts
  src/components/common/modal/ModalCloseButton.tsx
  src/components/common/title/Title.styled.ts
Labels: 🔧테스트

#193 이미지 최적화 (issue #192)
  src/components/common/avatar/AvartarList.tsx
  src/components/common/header/Header.tsx
  src/util/__tests__/formatImgPath.test.ts
  src/util/formatImgPath.ts
Labels: 🛠개선

#198 CDN 환경변수 스크립트에 추가
  .github/workflows/front_ci-cd.yml
Labels: 🔧테스트

#202 QA 개선 사항 반영
  src/components/common/sidebar/Sidebar.styled.ts
  src/components/common/sidebar/Sidebar.tsx
  src/components/manageProjects/CardList.styled.ts
  src/components/manageProjects/passNonPassList/PassNonPassItem.styled.ts
  src/constants/sidebarItems.tsx
  src/mock/mockProjectDetail.json
  src/mock/mockProjectList.json
  src/pages/manage/myProjectParticipantsPass/MyProjectVolunteersPass.tsx
  src/pages/manage/myProjectVolunteer/MyProjectVolunteer.tsx
Labels: 🛠개선

#212 사이드바 이미지 로드 개선
  index.html
  src/components/common/sidebar/Sidebar.tsx
Labels: 🛠개선

#215 헤더 프로필 기본이미지가 나오지 않는 이슈 (issue #214)
  src/components/common/header/Header.tsx
Labels: 👀버그

#220 프로젝트 생성 후 관리페이지 리패치 이슈
  src/hooks/useCreateProject.ts
Labels: 👀버그

#221 지원 후 지원 리스트(마이,유저페이지) 리패치 이슈 (issue #218)
  src/hooks/useApplyProject.ts
Labels: 🛠개선

#225 READ ME 이미지 수정 (issue #224)
  .storybook/test-runner.ts
  README.md
  src/assets/preview/applicationlist.png
  src/assets/preview/appliedlist.png
  src/assets/preview/apply.png
  src/assets/preview/change-password.png
  src/assets/preview/createproject.png
  src/assets/preview/joinedlist.png
  src/assets/preview/login.png
  src/assets/preview/main.png
  src/assets/preview/managelist.png
  src/assets/preview/mypage.png
  src/assets/preview/passnonpass.png
  src/assets/preview/projectdetail.png
  src/assets/preview/signup.png
  src/assets/preview/userpage.png
  src/assets/preview/userporjects.png
Labels: 📃문서
