Repository devpalsPlus/frontend, pull requests merged in 2025-04, with the labels that each got.

#232 Feat/#231
  src/api/http.api.ts
  src/api/joinProject.api.ts
  src/api/mypage.api.ts
  src/api/projectSearchFiltering.api.ts
  src/components/command/CommandLayout.styled.ts
  src/components/command/CommandLayout.tsx
  src/components/command/commandComponent/CommandComponent.styled.ts
  src/components/command/commandComponent/CommandComponent.tsx
  src/components/command/commandInput/CommandInput.styled.ts
  src/components/command/commandInput/CommandInput.tsx
  src/components/common/dropDown/DropDownItem.styled.ts
  src/components/common/dropDown/DropDownItem.tsx
  src/components/projectFormComponents/projectInformationInput/ProjectInformationInput.tsx
  src/components/projectFormComponents/projectInformationInput/fieldCategoryComponent/FieldCategoryComponent.tsx
  src/components/projectFormComponents/projectInformationInput/languageComponent/LanguageComponent.tsx
  src/components/projectFormComponents/projectInformationInput/positionComponent/PositionComponent.tsx
  src/components/projectFormComponents/projectInformationText/ProjectInformation.tsx
  src/constants/modalMessage.ts
  src/hooks/useDropDownItem.ts
  src/hooks/useInputFocus.ts
  src/hooks/useSearchFilteringSkillTag.ts
  src/models/createProject.ts
  src/models/projectDetail.ts
  src/models/tags.ts
  src/pages/createProject/CreateProject.tsx
  src/pages/modifyProject/ModifyProject.tsx
  src/pages/projectDetail/ProjectDetail.tsx
  src/routes/AppRoutes.tsx
  src/style/theme.ts
Labels: ⛏기능, 👀버그

#238 에러 status별 처리 개선 (issue: #234)
  src/App.tsx
  src/api/applicant.api.ts
  src/api/myProjectList.api.ts
  src/assets/wifi.svg
  src/components/common/avatar/AvatarList.tsx
  src/components/common/error/ErrorBoundary.tsx
  src/components/common/error/ErrorFallBack.styled.ts
  src/components/common/error/ErrorFallback.tsx
  src/components/common/error/QueryErrorBoundary.tsx
  src/components/manageProjects/Card.tsx
  src/components/manageProjects/ProjectHeader.tsx
  src/components/manageProjects/RecruitmentDate.tsx
  src/components/manageProjects/applicantInfo/ApplicantInfo.tsx
  src/components/manageProjects/applicantList/ApplicantItem.tsx
  src/components/manageProjects/applicantList/ApplicantList.tsx
  src/components/manageProjects/passNonPassList/PassNonPassItem.tsx
  src/components/manageProjects/passNonPassList/PassNonPassList.tsx
  src/constants/httpMessage.ts
  src/context/ErrorBoundaryContext.tsx
  src/hooks/useApllicantList.ts
  src/hooks/useApplicantInfo.ts
  src/hooks/useManagedProjects.ts
  src/mock/applicant.ts
  src/mock/manageProjectList.ts
  src/mock/mockApplicantData.json
  src/mock/mockApplicantsData.json
  src/mock/mockPassNonPassListData.json
  src/mock/mockProjectDetail.json
  src/mock/mockProjectList.json
  src/models/applicant.ts
  src/models/manageMyProject.ts
  src/pages/manage/myProjectList/MyProjectList.tsx
  src/pages/manage/myProjectParticipantsPass/MyProjectVolunteersPass.tsx
  src/pages/manage/myProjectVolunteer/MyProjectVolunteer.tsx
  src/routes/AppRoutes.tsx
Labels: 🛠개선

#240 댓글 API 적용 및 추가 기능 구현 (#issue 231)
  src/api/command.api.ts
  src/api/http.api.ts
  src/components/command/CommandLayout.styled.ts
  src/components/command/CommandLayout.tsx
  src/components/command/commandComponent/CommandComponent.styled.ts
  src/components/command/commandComponent/CommandComponent.tsx
  src/components/command/commandInput/CommandInput.styled.ts
  src/components/command/commandInput/CommandInput.tsx
  src/components/common/dropDown/DropDownItem.tsx
  src/components/common/header/Header.styled.ts
  src/components/common/header/Header.tsx
  src/components/common/header/Notification/Notification.styled.ts
  src/components/common/header/Notification/Notification.tsx
  src/components/common/header/Notification/NotificationItem/NotificationItem.styled.ts
  src/components/common/header/Notification/NotificationItem/NotificationItem.tsx
  src/components/projectFormComponents/projectInformationText/ProjectInformation.tsx
  src/components/projectFormComponents/stepComponent/StepComponent.tsx
  src/constants/commandConstants.tsx
  src/constants/routes.ts
  src/hooks/CommandHooks/useDeleteCommand.ts
  src/hooks/CommandHooks/useGetCommand.ts
  src/hooks/CommandHooks/usePostCommand.ts
  src/hooks/CommandHooks/usePutCommand.ts
  src/hooks/ProjectHooks/useApplyProject.ts
  src/hooks/ProjectHooks/useCreateProject.ts
  src/hooks/ProjectHooks/useMultiStepForm.ts
  src/hooks/ProjectHooks/useUpdateProject.ts
  src/hooks/queries/keys.ts
  src/hooks/useDropDownItem.ts
  src/hooks/useGetProjectData.ts
  src/hooks/useNotification.ts
  src/models/apiCommon.ts
  src/models/command.ts
  src/models/createProject.ts
  src/models/projectDetail.ts
  src/pages/apply/Apply.tsx
  src/pages/apply/ApplyStep.tsx
  src/pages/createProject/CreateProject.tsx
  src/pages/manage/myProjectVolunteer/MyProjectVolunteer.tsx
  src/pages/modifyProject/ModifyProject.tsx
  src/pages/projectDetail/ProjectDetail.tsx
Labels: ⛏기능

#243 랜딩페이지 구현 (issue #239)
  src/assets/arrow.svg
  src/assets/create.svg
  src/assets/landing.svg
  src/assets/manage_project.svg
  src/assets/project.svg
  src/assets/result_project.svg
  src/components/common/Button/Button.styled.ts
  src/components/projectFormComponents/projectInformationText/ProjectInformation.styled.ts
  src/constants/routes.ts
  src/hooks/useInView.ts
  src/mock/applicant.ts
  src/pages/main/About.styled.ts
  src/pages/main/Create.tsx
  src/pages/main/HeroSection.styled.ts
  src/pages/main/HeroSection.tsx
  src/pages/main/Index.tsx
  src/pages/main/Main.styled.ts
  src/pages/main/Main.tsx
  src/pages/main/Manage.tsx
  src/pages/main/Project.tsx
  src/pages/main/Result.tsx
  src/routes/AppRoutes.tsx
  src/style/theme.ts
Labels: ⛏기능

#246 마이 페이지에 평가도 부분 구현 issue #245
  package-lock.json
  package.json
  src/App.tsx
  src/api/alarm.api.ts
  src/api/chart.api.ts
  src/api/projectLists.api.ts
  src/assets/ArrowDown.svg
  src/assets/ArrowUp.svg
  src/assets/bell.svg
  src/assets/bellLogined.svg
  src/assets/chat.svg
  src/assets/dropdownButton.svg
  src/components/command/CommandLayout.styled.ts
  src/components/command/CommandLayout.tsx
  src/components/command/commandComponent/CommandComponent.tsx
  src/components/command/commandComponent/CommandComponent/CommandComponent.styled.ts
  src/components/command/commandComponent/CommandComponent/CommandComponent.tsx
  src/components/command/commandComponent/CommandComponentLayout.styled.ts
  src/components/command/commandComponent/CommandComponentLayout.tsx
  src/components/command/replyComponent/ReplyComponent.styled.ts
  src/components/command/replyComponent/ReplyComponent.tsx
  src/components/common/header/Header.tsx
  src/components/common/header/Notification/Notification.styled.ts
  src/components/common/header/Notification/Notification.tsx
  src/components/common/header/Notification/NotificationItem/NotificationItem.tsx
  src/components/common/skillTagBox/SkillTagBox.tsx
  src/components/mypage/myProfile/MyProfile.styled.ts
  src/components/mypage/myProfile/MyProfile.tsx
  src/components/projectFormComponents/projectInformationInput/ProjectInformationInput.tsx
  src/components/projectFormComponents/projectInformationInput/fieldCategoryComponent/FieldCategoryComponent.tsx
  src/components/projectFormComponents/projectInformationInput/languageComponent/LanguageComponent.tsx
  src/components/projectFormComponents/projectInformationInput/positionComponent/PositionComponent.tsx
  src/hooks/CommandHooks/useCommand.ts
  src/hooks/ProjectHooks/useCreateProject.ts
  src/hooks/ProjectHooks/useTagSelectors.ts
  src/hooks/ProjectHooks/useUpdateProject.ts
  src/hooks/queries/keys.ts
  src/hooks/useAlarmList.ts
  src/hooks/useChartData.ts
  src/hooks/useNotification.ts
  src/models/alarm.ts
  src/models/command.ts
  src/pages/createProject/CreateProject.tsx
  src/pages/modifyProject/ModifyProject.styled.ts
  src/pages/modifyProject/ModifyProject.tsx
  src/pages/projectDetail/ProjectDetail.styled.ts
Labels: ⛏기능, 🛠개선, 👀버그

#249 헤더, 랜딩페이지 웹 접근성 대응 (issue #244)
  src/components/common/dropDown/DropDown.tsx
  src/components/common/header/Header.styled.ts
  src/components/common/header/Header.tsx
  src/pages/main/About.styled.ts
  src/pages/main/HeroSection.styled.ts
  src/pages/main/HeroSection.tsx
  src/pages/manage/myProjectParticipantsPass/MyProjectVolunteersPass.tsx
Labels: ⛏기능

#250 마이페이지 알림 필터링 (#issue 242)
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/api/alarm.api.ts
  src/api/projectLists.api.ts
  src/components/common/header/Notification/Notification.tsx
  src/components/common/noContent/NoContent.styled.ts
  src/components/common/noContent/NoContent.tsx
  src/components/home/projectCardLists/cardList/CardList.tsx
  src/components/home/searchFiltering/filteringContents/filtering/Filtering.tsx
  src/components/mypage/ContentTab.styled.ts
  src/components/mypage/ContentTab.tsx
  src/components/mypage/activityLog/ActivityLog.tsx
  src/components/mypage/activityLog/commentsActivity/CommentsActivity.styled.ts
  src/components/mypage/activityLog/commentsActivity/CommentsActivity.tsx
  src/components/mypage/activityLog/inquiries/Inquiries.styled.ts
  src/components/mypage/activityLog/inquiries/Inquiries.tsx
  src/components/mypage/appliedProject/MyApplyProject.styled.ts
  src/components/mypage/appliedProject/MyApplyProject.tsx
  src/components/mypage/appliedProject/MyStatus.tsx
  src/components/mypage/joinedProject/MyJoinProjects.styled.ts
  src/components/mypage/joinedProject/MyJoinProjects.tsx
  src/components/mypage/myProfile/MyProfile.styled.ts
  src/components/mypage/myProfile/MyProfile.tsx
  src/components/mypage/notifications/Notifications.tsx
  src/components/mypage/notifications/all/All.styled.ts
  src/components/mypage/notifications/all/All.tsx
  src/components/mypage/notifications/appliedProjects/AppliedProjects.styled.ts
  src/components/mypage/notifications/appliedProjects/AppliedProjects.tsx
  src/components/mypage/notifications/appliedProjects/appliedProjectsStatus/AppliedProjectsStatus.styled.ts
  src/components/mypage/notifications/appliedProjects/appliedProjectsStatus/AppliedProjectsStatus.tsx
  src/constants/myPageFilter.ts
  src/constants/routes.ts
  src/hooks/useAlarmDelete.ts
  src/hooks/useAlarmList.ts
  src/hooks/useAlarmPatch.ts
  src/hooks/useProjectStatistic.ts
  src/hooks/useSearchFilteringSkillTag.ts
  src/models/alarm.ts
  src/pages/mypage/MyPage.styled.ts
  src/pages/mypage/MyPage.tsx
  src/routes/AppRoutes.tsx
Labels: ⛏기능, 🛠개선

#248 대댓글 CRUD 구현 issue #247
  src/api/comment.api.ts
  src/api/projectLists.api.ts
  src/api/reply.api.ts
  src/components/command/CommandLayout.tsx
  src/components/command/commandComponent/CommandComponent/CommandComponent.tsx
  src/components/command/replyComponent/ReplyComponent.tsx
  src/components/comment/CommentLayout.styled.ts
  src/components/comment/CommentLayout.tsx
  src/components/comment/commentComponent/CommentComponentLayout.styled.ts
  src/components/comment/commentComponent/CommentComponentLayout.tsx
  src/components/comment/commentComponent/commentComponent/CommentComponent.styled.ts
  src/components/comment/commentComponent/commentComponent/CommentComponent.tsx
  src/components/comment/commentInput/CommentInput.styled.ts
  src/components/comment/commentInput/CommentInput.tsx
  src/components/comment/replyComponent/ReplyComponent.styled.ts
  src/components/comment/replyComponent/ReplyComponent.tsx
  src/components/common/dropDown/DropDownItem.tsx
  src/constants/commandConstants.tsx
  src/hooks/CommandHooks/useDeleteCommand.ts
  src/hooks/CommandHooks/useGetCommand.ts
  src/hooks/CommentHooks/useComment.ts
  src/hooks/CommentHooks/useDeleteComment.ts
  src/hooks/CommentHooks/useDeleteReply.ts
  src/hooks/CommentHooks/useGetComment.ts
  src/hooks/CommentHooks/useGetReply.ts
  src/hooks/CommentHooks/usePatchReply.ts
  src/hooks/CommentHooks/usePostComment.ts
  src/hooks/CommentHooks/usePostReply.ts
  src/hooks/CommentHooks/usePutComment.ts
  src/hooks/ProjectHooks/useUpdateProject.ts
  src/hooks/queries/keys.ts
  src/models/alarm.ts
  src/models/command.ts
  src/models/comment.ts
  src/pages/projectDetail/ProjectDetail.tsx
Labels: ⛏기능, 🛠개선

#258 워크플로우 개선을 통한 CI속도 개선(issue #257)
  .github/workflows/ui-test.yml
Labels: 🛠개선

#259 문의하기 ui api 연결 (#issue 256)
  src/api/inquiry.api.ts
  src/components/common/header/Header.tsx
  src/components/home/searchFiltering/filteringContents/FilteringContents.styled.ts
  src/components/home/searchFiltering/filteringContents/FilteringContents.tsx
  src/components/home/searchFiltering/filteringContents/filtering/Filtering.styled.ts
  src/components/home/searchFiltering/filteringContents/filtering/Filtering.tsx
  src/components/mypage/ContentTab.tsx
  src/components/mypage/activityLog/ActivityLog.tsx
  src/components/mypage/notifications/Notifications.tsx
  src/components/userPage/joinedProject/UserJoinProject.tsx
  src/constants/customerService.ts
  src/constants/myPageFilter.ts
  src/hooks/usePostInquiry.ts
  src/models/inquiry.ts
  src/models/userProject.ts
  src/pages/customerService/CustomerServiceHeader.styled.ts
  src/pages/customerService/CustomerServiceHeader.tsx
  src/pages/customerService/MoveInquiredLink.styled.ts
  src/pages/customerService/MoveInquiredLink.tsx
  src/pages/customerService/faq/FAQ.styled.ts
  src/pages/customerService/faq/FAQ.tsx
  src/pages/customerService/inquiry/Inquiry.styled.ts
  src/pages/customerService/inquiry/Inquiry.tsx
  src/pages/customerService/notice/Notice.styled.ts
  src/pages/customerService/notice/Notice.tsx
  src/routes/AppRoutes.tsx
Labels: ⛏기능
